name: Build

on:
  workflow_call:
    inputs:
      node_version:
        required: true
        type: string
        default: 20

jobs:
  build-playground:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Install dependencies
        uses: ./.github/actions/install-dependencies
        with:
          node_version: ${{ inputs.node_version }}
          pnpm_version: 9
          cache: 'pnpm'

      - name: Build the module (prepack)
        run: pnpm --filter nuxt-compose-icons prepack

      - name: Prepare playground
        run: pnpm --filter ./packages/nuxt/playground exec nuxi prepare

      - name: Build playground
        run: pnpm --filter ./packages/nuxt/playground exec nuxi build

      - name: Upload-artifact
        uses: actions/upload-artifact@v6
        with:
          name: playground-build
          path: ./packages/nuxt/playground/.output/public/

  build-and-deploy-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install dependencies
        uses: ./.github/actions/install-dependencies
        with:
          node_version: ${{ inputs.node_version }}
          pnpm_version: 9
          cache: 'pnpm'

      - name: Build with VitePress
        run: pnpm docs:build

      - name: Upload-artifact
        uses: actions/upload-artifact@v6
        with:
          name: docs-build
          path: ./docs/.vitepress/dist/
