name: Run Tests

on:
  workflow_call:
    inputs:
      node_version:
        required: true
        type: number
        default: 20

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Install dependencies
        uses: ./.github/actions/install-dependencies
        with:
          node_version: ${{ inputs.node_version }}
          pnpm_version: 9
          cache: pnpm

      - name: Prepare playground
        run: pnpm --filter ./packages/nuxt/playground exec nuxi prepare

      - name: Install Playwright browsers
        run: pnpm exec playwright-core install --with-deps

      - name: Run tests
        run: pnpm test

      - name: Upload HTML report
        if: ${{ !cancelled() }}
        uses: actions/upload-artifact@v6
        with:
          name: test-coverage-${{ inputs.node_version }}
          path: packages/nuxt/test/coverage
          retention-days: 30

      - name: Upload Screenshot
        if: ${{ !cancelled() }}
        uses: actions/upload-artifact@v6
        with:
          name: screenshot-${{ inputs.node_version }}
          path: packages/nuxt/test/screenshots/screenshot.jpeg
          retention-days: 30
